In [36]:
import pandas as pd

data = ""

pd.set_option("display.max_columns", 80) #lets you see all the columns in the dataframe
pd.set_option("display.max_rows", 30)

In [37]:
df = pd.read_csv("ondedoi_responses_public - combined.csv")

In [38]:
df.shape

(187, 15)

In [39]:
df.columns

Index(['Timestamp',
       '1 - Você já foi vítima de algum tipo de abuso sexual por parte de um profissional da saúde, como toques ou comentários inapropriados?',
       '2 - Como você se identifica?', '4 - Quantos anos você tem?',
       '3 - Qual a sua classe social?',
       '5 - Com qual gênero você se identifica?',
       '4 - Qual é a sua orientação sexual?',
       '5 - Que tipo de abuso sexual você sofreu? (marque quantas forem necessárias)',
       '6 - Em que local ocorreu o abuso?',
       '10 - Quantos anos você tinha quando o abuso aconteceu?',
       '9 - Qual era a especialidade do profissional?',
       '11 - Em qual estado aconteceu o abuso?',
       '12 - Em qual cidade aconteceu o abuso?', '15 - Você fez uma denúncia?',
       '16 - Como foi a sua experiência no processo de Denúncia? (marque quantas forem necessárias)'],
      dtype='str')

In [40]:
df.head()

,Timestamp,"1 - Você já foi vítima de algum tipo de abuso sexual por parte de um profissional da saúde, como toques ou comentários inapropriados?",2 - Como você se identifica?,4 - Quantos anos você tem?,3 - Qual a sua classe social?,5 - Com qual gênero você se identifica?,4 - Qual é a sua orientação sexual?,5 - Que tipo de abuso sexual você sofreu? (marque quantas forem necessárias),6 - Em que local ocorreu o abuso?,10 - Quantos anos você tinha quando o abuso aconteceu?,9 - Qual era a especialidade do profissional?,11 - Em qual estado aconteceu o abuso?,12 - Em qual cidade aconteceu o abuso?,15 - Você fez uma denúncia?,16 - Como foi a sua experiência no processo de Denúncia? (marque quantas forem necessárias)
0,3/4/2020 14:35:13,"Sim, por um profissional da saúde homem",Branca,18-25,Classe E - Renda mensal familiar até R$ 1.254,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Violação sexual mediante fraude (Tocar de mane...,Posto de saúde,2-5,NaN,Rio Grande do Sul,Cachoeira do sul,Não,NaN
1,8/28/2020 11:05:39,"Sim, por um profissional da saúde homem",Branca,36-40,Classe C - Renda mensal familiar até R$ 8.640,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Estupro de vulnerável (quando a vítima é menor...,Clínica particular,2-5,Pediatra,Minas Gerais,Belo Horizonte,Não,NaN
2,2/22/2020 1:25:03,"Sim, por uma profissional da saúde mulher",Branca,18-25,Classe C - Renda mensal familiar até R$ 8.640,"Mulher Cis (me identifico, em todos os aspecto...",Bissexual,Violação sexual mediante fraude (Tocar de mane...,Hospital público,6-10,Pediatra,Minas Gerais,Poços de Caldas,Não,NaN
3,3/4/2020 16:14:33,"Sim, por um profissional da saúde homem",Branca,26-30,Classe C - Renda mensal familiar até R$ 8.640,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Violação sexual mediante fraude (Tocar de mane...,Clínica particular,11-15,Ginecologista,São Paulo,Guarulhos,Não,NaN
4,5/4/2020 20:49:37,"Sim, por um profissional da saúde homem",Branca,36-40,Classe A - Renda mensal familiar acima de R$11...,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Importunação sexual (Beijos forçados e toques ...,Clínica particular,11-15,"foram três: um ginecologista, um clinico geral...",São Paulo,São Paulo,Não,NaN

In [41]:
types_abuse = df["5 - Que tipo de abuso sexual você sofreu? (marque quantas forem necessárias)"].value_counts(dropna=False)
print(types_abuse)

5 - Que tipo de abuso sexual você sofreu? (marque quantas forem necessárias)
Violação sexual mediante fraude (Tocar de maneira imprópria fazendo a paciente pensar que era parte do procedimento médico)                                                                                                                                                                                                                                                                     79
Injúria (Cantadas e palavras ofensivas)                                                                                                                                                                                                                                                                                                                                                         26
Importunação sexual (Beijos forçados e toques sem permissão), Violação sexual mediante fraude (Tocar de maneira imprópria fazendo a paciente pensar que era parte do procedimento médico)                                                                                                                                                                                                       20
Violação sexual mediante fraude (Tocar de maneira imprópria fazendo a paciente pensar que era parte do procedimento médico), Injúria (Cantadas e palavras ofensivas)                                                                                                                                                                                                                            19
Importunação sexual (Beijos forçados e toques sem permissão)                                                                                                                                                                                                                                                                                                                                    13
Importunação sexual (Beijos forçados e toques sem permissão), Violação sexual mediante fraude (Tocar de maneira imprópria fazendo a paciente pensar que era parte do procedimento médico), Injúria (Cantadas e palavras ofensivas)                                                                                                                                                              13
NaN                                                                                                                                                                                                                                                                                                                                                                                              5
Importunação sexual (Beijos forçados e toques sem permissão), Injúria (Cantadas e palavras ofensivas)                                                                                                                                                                                                                                                                                            5
Estupro de vulnerável (quando a vítima é menor de 14 anos ou esta sob efeito de medicação)                                                                                                                                                                                                                                                                                                       2
Estupro de vulnerável (quando a vítima é menor de 14 anos ou está sob efeito de medicação)                                                                                                                                                                                                                                                                                                       1
Violação sexual mediante fraude (Tocar de maneira imprópria fazendo a paciente pensar que era parte do procedimento médico), Estupro de vulnerável (quando a vítima é menor de 14 anos ou está sob efeito de medicação)                                                                                                                                                                          1
Importunação sexual (Beijos forçados e toques sem permissão), Violação sexual mediante fraude (Tocar de maneira imprópria fazendo a paciente pensar que era parte do procedimento médico), Injúria (Cantadas e palavras ofensivas), Estupro (Ato sexual utilizando de violência ou grave ameaça), Estupro de vulnerável (quando a vítima é menor de 14 anos ou esta sob efeito de medicação)     1
Injúria (Cantadas e palavras ofensivas), Estupro de vulnerável (quando a vítima é menor de 14 anos ou está sob efeito de medicação)                                                                                                                                                                                                                                                              1
Importunação sexual (Beijos forçados e toques sem permissão), Estupro de vulnerável (quando a vítima é menor de 14 anos ou esta sob efeito de medicação)                                                                                                                                                                                                                                         1
Name: count, dtype: int64

In [42]:
#Issue: lots of options that are the same thing but have different spellings... I ended up fixing the spelling on the CSV and reloading it.

In [43]:
## Renaming columns to make things easier using df.rename(columns={"old name": "new name"}, inplace=True)
df.rename(columns={"5 - Que tipo de abuso sexual você sofreu? (marque quantas forem necessárias)": "types_abuse"}, inplace=True)

In [44]:
unique_values = df["types_abuse"].str.split(',').explode().str.strip().unique()
print(unique_values)

<StringArray>
['Violação sexual mediante fraude (Tocar de maneira imprópria fazendo a paciente pensar que era parte do procedimento médico)',
                                  'Estupro de vulnerável (quando a vítima é menor de 14 anos ou está sob efeito de medicação)',
                                                                'Importunação sexual (Beijos forçados e toques sem permissão)',
                                                                                     'Injúria (Cantadas e palavras ofensivas)',
                                                                'Estupro (Ato sexual utilizando de violência ou grave ameaça)',
                                  'Estupro de vulnerável (quando a vítima é menor de 14 anos ou esta sob efeito de medicação)',
                                                                                                                           nan]
Length: 7, dtype: str

In [45]:
#Count values with different spellings
#count = df["column"].fillna("").str.contains(r"Viola[cç][aã]o sexual mediante fraude", regex=True).sum()
#print(count)

#TYPE OF SEXUAL ABUSE (COUNT AND PERCENTAGE)

In [46]:
#RAPE OF A VULNERABLE PERSON OR CHILD aka ESTUPRO DE VULNERÁVEL in Portuguese.
count = df["types_abuse"].fillna("").str.contains(r"est[aá] sob efeito de medicação", regex=True).sum()
print(count)
print(f"percentage: {count/len(df)*100:.1f}%")

7
percentage: 3.7%

In [47]:
#SEXUAL ASSAULT BY FRAUD OR DECEPTION aka VIOLAÇÃO SEXUAL MEDIANTE FRAUDE in Portuguese.
count = df['types_abuse'].fillna("").str.contains("Violação sexual mediante fraude").sum()
print(count)
print(f"percentage: {count/len(df)*100:.1f}%")

133
percentage: 71.1%

In [48]:
#VERBAL SEXUAL ABUSE aka INJÚRIA in Portuguese.
count = df['types_abuse'].fillna("").str.contains("Injúria").sum()
print(count)
print(f"percentage: {count/len(df)*100:.1f}%")

65
percentage: 34.8%

In [49]:
#RAPE aka ESTUPRO in Portuguese.
count = df['types_abuse'].fillna("").str.contains("grave ameaça").sum()
print(count)
print(f"percentage: {count/len(df)*100:.1f}%")

1
percentage: 0.5%

In [50]:
#UNWANTED ADVANCES aka IMPORTUNAÇÃO in Portuguese.
count = df['types_abuse'].fillna("").str.contains("Importunação").sum()
print(count)
print(f"percentage: {count/len(df)*100:.1f}%")

53
percentage: 28.3%

GENDER OF VICTIMS (COUNT AND PERCENTAGE)

In [51]:
df.rename(columns={"5 - Com qual gênero você se identifica?": "victim_gender"}, inplace=True)

In [52]:
#CIS WOMEN
count = df["victim_gender"].fillna("").str.contains("Mulher Cis").sum()
print(count)
print(f"percentage: {count/len(df)*100:.1f}%")

180
percentage: 96.3%

In [53]:
#CIS MEN
count = df["victim_gender"].fillna("").str.contains("Homem Cis").sum()
print(count)
print(f"percentage: {count/len(df)*100:.1f}%")

4
percentage: 2.1%

In [54]:
print(df["victim_gender"].value_counts(dropna=True))
print((df["victim_gender"].value_counts(normalize=True, dropna=True) * 100).round(1))

victim_gender
Mulher Cis (me identifico, em todos os aspectos, com o meu “gênero de nascença”.)    180
Homem Cis (me identifico, em todos os aspectos, com o meu “gênero de nascença”.)       4
Não Binário                                                                            2
Não-Binárie                                                                            1
Name: count, dtype: int64
victim_gender
Mulher Cis (me identifico, em todos os aspectos, com o meu “gênero de nascença”.)    96.3
Homem Cis (me identifico, em todos os aspectos, com o meu “gênero de nascença”.)      2.1
Não Binário                                                                           1.1
Não-Binárie                                                                           0.5
Name: proportion, dtype: float64

RACE OF VICTIMS (COUNT AND PERCENTAGE)

In [55]:
df.rename(columns={"2 - Como você se identifica?": "victim_race"}, inplace=True)

In [56]:
print(df["victim_race"].value_counts(dropna=False))
print((df["victim_race"].value_counts(normalize=True, dropna=True) * 100).round(1))

victim_race
Branca     121
Parda       45
Negra       18
Amarela      3
Name: count, dtype: int64
victim_race
Branca     64.7
Parda      24.1
Negra       9.6
Amarela     1.6
Name: proportion, dtype: float64

ECONOMIC STATUS OF VICTIMS (COUNT AND PERCENTAGE)

In [57]:
df.rename(columns={"3 - Qual a sua classe social?": "victim_econ_status"}, inplace=True)
print((df["victim_econ_status"].value_counts(normalize=True, dropna=True) * 100).round(1))

victim_econ_status
Classe C - Renda mensal familiar até    R$ 8.640      50.3
Classe D - Renda mensal familiar até   R$ 2.004       17.1
Classe A - Renda mensal familiar acima de R$11.261    15.0
Classe E - Renda mensal familiar até   R$ 1.254       11.2
Classe B - Renda mensal familiar até   R$ 11.261       6.4
Name: proportion, dtype: float64

VICTIM'S AGE AT THE TIME OF THE OFFENSE (AVERAGE, PERCENTAGE)

In [58]:
df.rename(columns={"10 - Quantos anos você tinha quando o abuso aconteceu?": "victim_age"}, inplace=True)
print(df["victim_age"].value_counts(dropna=True))
print((df["victim_age"].value_counts(normalize=True, dropna=True) * 100).round(1))

victim_age
20-30    64
16-20    48
31-40    32
11-15    24
41-50     5
6-10      4
18-30     4
2-5       2
15-17     2
50+       2
Name: count, dtype: int64
victim_age
20-30    34.2
16-20    25.7
31-40    17.1
11-15    12.8
41-50     2.7
6-10      2.1
18-30     2.1
2-5       1.1
15-17     1.1
50+       1.1
Name: proportion, dtype: float64

#Make a note that 4 rows were distorted, make them NA and continue to work with rows for other ones.

In [59]:
df[df['victim_age'] == '18-30']

,Timestamp,"1 - Você já foi vítima de algum tipo de abuso sexual por parte de um profissional da saúde, como toques ou comentários inapropriados?",victim_race,4 - Quantos anos você tem?,victim_econ_status,victim_gender,4 - Qual é a sua orientação sexual?,types_abuse,6 - Em que local ocorreu o abuso?,victim_age,9 - Qual era a especialidade do profissional?,11 - Em qual estado aconteceu o abuso?,12 - Em qual cidade aconteceu o abuso?,15 - Você fez uma denúncia?,16 - Como foi a sua experiência no processo de Denúncia? (marque quantas forem necessárias)
77,9/30/2020 15:51:47,"Sim, por um profissional da saúde homem",Branca,18-25,Classe C - Renda mensal familiar até R$ 8.640,"Homem Cis (me identifico, em todos os aspectos...",Heterossexual,Violação sexual mediante fraude (Tocar de mane...,Clínica particular,18-30,Clínico Geral,Santa Catarina,Florianópolis,Não,NaN
78,10/7/2020 16:58:59,"Sim, por um profissional da saúde homem",Branca,26-30,Classe A - Renda mensal familiar acima de R$11...,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Violação sexual mediante fraude (Tocar de mane...,Clínica particular,18-30,nutrologo,São Paulo,são paulo,Sim,Prefiro não falar sobre o assunto
79,11/10/2020 22:25:43,"Sim, por um profissional da saúde homem",Branca,31-35,Classe A - Renda mensal familiar acima de R$11...,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Violação sexual mediante fraude (Tocar de mane...,Hospital público,18-30,Clínico Geral,São Paulo,São Paulo,Não,NaN
80,12/14/2020 18:19:36,"Sim, por um profissional da saúde homem",Parda,26-30,Classe C - Renda mensal familiar até R$ 8.640,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Violação sexual mediante fraude (Tocar de mane...,Clínica particular,18-30,Dermatologista,Distrito Federal,Exterior - Quito - Equador,Não,NaN

#this data has a problem since the age ranges are random and make it hard to get a real sense of whether these crimes were committed against a minor (under 18) and qualify as aggravated offense (when the victim is under 14). Also, 18-30 overlaps with 20-30, while 16-20 overlaps with 20-30. Ask Nina about inconsistencies with the age ranges.

REPORTED OFFENSE Y or N (COUNT, PERCENTAGE)

In [60]:
df.rename(columns={"15 - Você fez uma denúncia?": "offense_reported"}, inplace=True)
print((df["offense_reported"].value_counts(normalize=True, dropna=True) * 100).round(1))

offense_reported
Não    85.5
Sim    14.5
Name: proportion, dtype: float64

LOCATION OF OFFENSE (🇧🇷 STATE) COUNT AND PERCENTAGE

In [61]:
df.rename(columns={"11 - Em qual estado aconteceu o abuso?": "offense_state"}, inplace=True)
print((df["offense_state"].value_counts(normalize=True, dropna=True) * 100).round(1))

offense_state
São Paulo              34.2
Minas Gerais           12.3
Rio de Janeiro         10.7
Bahia                   7.0
Rio Grande do Sul       5.3
Paraná                  5.3
Goiás                   4.8
Pernambuco              4.8
Santa Catarina          3.7
Distrito Federal        2.1
Pará                    1.6
Tocantins               1.1
Ceará                   1.1
Amazonas                1.1
Alagoas                 0.5
Paraíba                 0.5
Amapá                   0.5
Piauí                   0.5
Rio Grande do Norte     0.5
Sergipe                 0.5
Mato Grosso             0.5
Maranhão                0.5
Acre                    0.5
Name: proportion, dtype: float64

LOCATION OF OFFENSE (COUNTRY REGION) COUNT AND PERCENTAGE

In [62]:
#From Luiza, TA
#1 create list of states for each region in the country

In [63]:
#Regions of Brazil
Sudeste = ["São Paulo", "Minas Gerais", "Rio de Janeiro", "Espírito Santo"]
Nordeste = ["Bahia", "Pernambuco", "Ceará", "Maranhão", "Paraíba", "Piauí", "Rio Grande do Norte", "Alagoas", "Sergipe"]
Sul = ["Paraná", "Santa Catarina", "Rio Grande do Sul"]
Norte = ["Amazonas", "Pará", "Rondônia", "Roraima", "Amapá", "Acre", "Tocantins"]
Centro_Oeste = ["Goiás", "Mato Grosso", "Mato Grosso do Sul", "Distrito Federal"]

In [64]:
#2. Create an empty list to store the results row-by-row regions_list = [] 
#3. Loop through each row of the DataFrame for index, row in df.iterrows(): 

regions_list = [] 
for index, row in df.iterrows():
    # Get the state from the current row
    state = row["offense_state"]

    ## # Get the state from the current row state = row["state"] # Check which list the state belongs to if state in Sudeste: regions_list.append("Sudeste") elif state in Nordeste: regions_list.append("Nordeste") elif state in Sul: regions_list.append("Sul") elif state in Norte: regions_list.append("Norte") elif state in Centro-Oeste: regions_list.append("Centro-Oeste") else: regions_list.append("Unknown") 

    # Check which list the state belongs to
    if state in Sudeste:
        regions_list.append("Sudeste")
    elif state in Nordeste:
        regions_list.append("Nordeste")
    elif state in Sul:
        regions_list.append("Sul")
    elif state in Norte:
        regions_list.append("Norte")
    elif state in Centro_Oeste:
        regions_list.append("Centro-Oeste")
    else:
        regions_list.append("Unknown")

In [65]:
#4. Assign the completed list as your new columndf["region"] = regions_list
df["region"] = regions_list

In [66]:
df

,Timestamp,"1 - Você já foi vítima de algum tipo de abuso sexual por parte de um profissional da saúde, como toques ou comentários inapropriados?",victim_race,4 - Quantos anos você tem?,victim_econ_status,victim_gender,4 - Qual é a sua orientação sexual?,types_abuse,6 - Em que local ocorreu o abuso?,victim_age,9 - Qual era a especialidade do profissional?,offense_state,12 - Em qual cidade aconteceu o abuso?,offense_reported,16 - Como foi a sua experiência no processo de Denúncia? (marque quantas forem necessárias),region
0,3/4/2020 14:35:13,"Sim, por um profissional da saúde homem",Branca,18-25,Classe E - Renda mensal familiar até R$ 1.254,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Violação sexual mediante fraude (Tocar de mane...,Posto de saúde,2-5,NaN,Rio Grande do Sul,Cachoeira do sul,Não,NaN,Sul
1,8/28/2020 11:05:39,"Sim, por um profissional da saúde homem",Branca,36-40,Classe C - Renda mensal familiar até R$ 8.640,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Estupro de vulnerável (quando a vítima é menor...,Clínica particular,2-5,Pediatra,Minas Gerais,Belo Horizonte,Não,NaN,Sudeste
2,2/22/2020 1:25:03,"Sim, por uma profissional da saúde mulher",Branca,18-25,Classe C - Renda mensal familiar até R$ 8.640,"Mulher Cis (me identifico, em todos os aspecto...",Bissexual,Violação sexual mediante fraude (Tocar de mane...,Hospital público,6-10,Pediatra,Minas Gerais,Poços de Caldas,Não,NaN,Sudeste
3,3/4/2020 16:14:33,"Sim, por um profissional da saúde homem",Branca,26-30,Classe C - Renda mensal familiar até R$ 8.640,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Violação sexual mediante fraude (Tocar de mane...,Clínica particular,11-15,Ginecologista,São Paulo,Guarulhos,Não,NaN,Sudeste
4,5/4/2020 20:49:37,"Sim, por um profissional da saúde homem",Branca,36-40,Classe A - Renda mensal familiar acima de R$11...,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Importunação sexual (Beijos forçados e toques ...,Clínica particular,11-15,"foram três: um ginecologista, um clinico geral...",São Paulo,São Paulo,Não,NaN,Sudeste
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,9/29/2020 14:12:58,"Sim, por um profissional da saúde homem",Parda,50+,Classe C - Renda mensal familiar até R$ 8.640,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Importunação sexual (Beijos forçados e toques ...,Hospital particular,50+,Clinica Medica,São Paulo,Sao Paulo,Sim,Não senti que o meu caso teve a devida atenção...,Sudeste
183,12/22/2019 18:05:08,"Sim, por um profissional da saúde homem",Branca,50+,Classe A - Renda mensal familiar acima de R$11...,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Importunação sexual (Beijos forçados e toques ...,Clínica particular,50+,Genicologista,São Paulo,Florianópolis,Sim,Positiva. Senti que os profissionais de atendi...,Sudeste
184,12/15/2019 21:31:44,"Sim, por um profissional da saúde homem",Branca,46-50,Classe A - Renda mensal familiar acima de R$11...,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Estupro de vulnerável (quando a vítima é menor...,Clínica particular,6-10,Psicólogo Psiquiatra,Rio de Janeiro,Rio de Janeiro,Não,NaN,Sudeste
185,12/21/2019 16:03:35,"Sim, por um profissional da saúde homem",Negra,36-40,Classe C - Renda mensal familiar até R$ 8.640,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Estupro de vulnerável (quando a vítima é menor...,Hospital público,6-10,"Eu acho que era pediatra, mas não lembro.",Goiás,Goiânia,Não,NaN,Centro-Oeste
186,1/6/2020 13:31:21,"Sim, por um profissional da saúde homem",Branca,41-45,Classe C - Renda mensal familiar até R$ 8.640,"Homem Cis (me identifico, em todos os aspectos...",Heterossexual,Violação sexual mediante fraude (Tocar de mane...,Hospital público,6-10,Pediatra,São Paulo,rio claro,Não,NaN,Sudeste

In [67]:
print(df["region"].value_counts(dropna=True))
print((df["region"].value_counts(normalize=True, dropna=True) * 100).round(1))

region
Sudeste         107
Nordeste         30
Sul              27
Centro-Oeste     14
Norte             9
Name: count, dtype: int64
region
Sudeste         57.2
Nordeste        16.0
Sul             14.4
Centro-Oeste     7.5
Norte            4.8
Name: proportion, dtype: float64

LOCATION OF OFFENSE (TYPE OF MEDICAL PRACTICE)

In [68]:
df.rename(columns={"6 - Em que local ocorreu o abuso?": "offense_location"}, inplace=True)

In [69]:
print(df["offense_location"].value_counts(dropna=True))

offense_location
Clínica particular                                            112
Hospital particular                                            31
Posto de saúde                                                 17
Hospital público                                               17
Consultório de sede de plano de saúde                           1
Hospital e clínica particular                                   1
Clínica particular também                                       1
Consultorio Dentista                                            1
Doação de Sangue em Hospital Público - HEMORIO                  1
consultório particular do médico                                1
atendimento odontológico da universidade federal do paraná      1
Juizado federal                                                 1
Policlina, centro de especialidades publica                     1
espaco terapeutico de . TAntra                                  1
Name: count, dtype: int64

In [70]:
#Creating a dictionary to group locations to show if they are practices vs hospitals, and free vs paid.
location_map = { "Clínica particular": "Private practice", 
"Clínica particular também": "Private practice", "Consultório de sede de plano de saúde": "Private practice", "consultório particular do médico": "Private practice", "Hospital particular": "Private hospital", "Hospital e clínica particular":"Private hospital", "Posto de saúde": "Free Clinic", "Juizado federal": "Other", "Hospital público": "Free hospital", "Doação de Sangue em Hospital Público - HEMORIO": "Other", "Policlina, centro de especialidades publica": "Free hospital", "espaco terapeutico de . TAntra": "Other", "Consultorio Dentista": "Other", "atendimento odontológico da universidade federal do paraná": "Other"
}

#Then create a column 
df["offense_location_clean"] = (
    df["offense_location"]
    .str.strip()
    .replace(location_map)
)

In [71]:
df

,Timestamp,"1 - Você já foi vítima de algum tipo de abuso sexual por parte de um profissional da saúde, como toques ou comentários inapropriados?",victim_race,4 - Quantos anos você tem?,victim_econ_status,victim_gender,4 - Qual é a sua orientação sexual?,types_abuse,offense_location,victim_age,9 - Qual era a especialidade do profissional?,offense_state,12 - Em qual cidade aconteceu o abuso?,offense_reported,16 - Como foi a sua experiência no processo de Denúncia? (marque quantas forem necessárias),region,offense_location_clean
0,3/4/2020 14:35:13,"Sim, por um profissional da saúde homem",Branca,18-25,Classe E - Renda mensal familiar até R$ 1.254,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Violação sexual mediante fraude (Tocar de mane...,Posto de saúde,2-5,NaN,Rio Grande do Sul,Cachoeira do sul,Não,NaN,Sul,Free Clinic
1,8/28/2020 11:05:39,"Sim, por um profissional da saúde homem",Branca,36-40,Classe C - Renda mensal familiar até R$ 8.640,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Estupro de vulnerável (quando a vítima é menor...,Clínica particular,2-5,Pediatra,Minas Gerais,Belo Horizonte,Não,NaN,Sudeste,Private practice
2,2/22/2020 1:25:03,"Sim, por uma profissional da saúde mulher",Branca,18-25,Classe C - Renda mensal familiar até R$ 8.640,"Mulher Cis (me identifico, em todos os aspecto...",Bissexual,Violação sexual mediante fraude (Tocar de mane...,Hospital público,6-10,Pediatra,Minas Gerais,Poços de Caldas,Não,NaN,Sudeste,Free hospital
3,3/4/2020 16:14:33,"Sim, por um profissional da saúde homem",Branca,26-30,Classe C - Renda mensal familiar até R$ 8.640,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Violação sexual mediante fraude (Tocar de mane...,Clínica particular,11-15,Ginecologista,São Paulo,Guarulhos,Não,NaN,Sudeste,Private practice
4,5/4/2020 20:49:37,"Sim, por um profissional da saúde homem",Branca,36-40,Classe A - Renda mensal familiar acima de R$11...,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Importunação sexual (Beijos forçados e toques ...,Clínica particular,11-15,"foram três: um ginecologista, um clinico geral...",São Paulo,São Paulo,Não,NaN,Sudeste,Private practice
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,9/29/2020 14:12:58,"Sim, por um profissional da saúde homem",Parda,50+,Classe C - Renda mensal familiar até R$ 8.640,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Importunação sexual (Beijos forçados e toques ...,Hospital particular,50+,Clinica Medica,São Paulo,Sao Paulo,Sim,Não senti que o meu caso teve a devida atenção...,Sudeste,Private hospital
183,12/22/2019 18:05:08,"Sim, por um profissional da saúde homem",Branca,50+,Classe A - Renda mensal familiar acima de R$11...,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Importunação sexual (Beijos forçados e toques ...,Clínica particular,50+,Genicologista,São Paulo,Florianópolis,Sim,Positiva. Senti que os profissionais de atendi...,Sudeste,Private practice
184,12/15/2019 21:31:44,"Sim, por um profissional da saúde homem",Branca,46-50,Classe A - Renda mensal familiar acima de R$11...,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Estupro de vulnerável (quando a vítima é menor...,Clínica particular,6-10,Psicólogo Psiquiatra,Rio de Janeiro,Rio de Janeiro,Não,NaN,Sudeste,Private practice
185,12/21/2019 16:03:35,"Sim, por um profissional da saúde homem",Negra,36-40,Classe C - Renda mensal familiar até R$ 8.640,"Mulher Cis (me identifico, em todos os aspecto...",Heterossexual,Estupro de vulnerável (quando a vítima é menor...,Hospital público,6-10,"Eu acho que era pediatra, mas não lembro.",Goiás,Goiânia,Não,NaN,Centro-Oeste,Free hospital
186,1/6/2020 13:31:21,"Sim, por um profissional da saúde homem",Branca,41-45,Classe C - Renda mensal familiar até R$ 8.640,"Homem Cis (me identifico, em todos os aspectos...",Heterossexual,Violação sexual mediante fraude (Tocar de mane...,Hospital público,6-10,Pediatra,São Paulo,rio claro,Não,NaN,Sudeste,Free hospital

In [72]:
offense_location_clean_counts = df["offense_location_clean"].value_counts(dropna=True)
print(offense_location_clean_counts)

offense_location_clean
Private practice    115
Private hospital     32
Free hospital        18
Free Clinic          17
Other                 5
Name: count, dtype: int64

PERPETRATOR'S GENDER

In [73]:
df.rename(columns={"1 - Você já foi vítima de algum tipo de abuso sexual por parte de um profissional da saúde, como toques ou comentários inapropriados?": "perp_gender"}, inplace=True)
print(df["perp_gender"].value_counts(dropna=True))
print((df["perp_gender"].value_counts(normalize=True, dropna=True) * 100).round(1))

perp_gender
Sim, por um profissional da saúde homem      171
Sim, por uma profissional da saúde mulher     16
Name: count, dtype: int64
perp_gender
Sim, por um profissional da saúde homem      91.4
Sim, por uma profissional da saúde mulher     8.6
Name: proportion, dtype: float64

PERPETRATOR'S MEDICAL SPECIALTY (COUNT, PERCENTAGE)

In [74]:
df.rename(columns ={"9 - Qual era a especialidade do profissional?": "perp_specialty"}, inplace=True)
print(df["perp_specialty"].value_counts(dropna=True))
print((df["perp_specialty"].value_counts(normalize=True, dropna=True) * 100).round(1))

perp_specialty
Ginecologista                                36
Ginecologista                                11
Pediatra                                      7
Cardiologista                                 5
Ortopedista                                   5
                                             ..
Mastologista                                  1
Terapeuta tantrico                            1
Clinica Medica                                1
Psicólogo Psiquiatra                          1
Eu acho que era pediatra, mas não lembro.     1
Name: count, Length: 97, dtype: int64
perp_specialty
Ginecologista                                19.9
Ginecologista                                 6.1
Pediatra                                      3.9
Cardiologista                                 2.8
Ortopedista                                   2.8
                                             ...
Mastologista                                  0.6
Terapeuta tantrico                            0.6
Clinica Medica                                0.6
Psicólogo Psiquiatra                          0.6
Eu acho que era pediatra, mas não lembro.     0.6
Name: proportion, Length: 97, dtype: float64

#Standardizing the data in a column that aggregates specialties regardless of spelling or number of specialties listed.
#1 Decide if you want to count responses or mentions (some include two)
#2 Give the list to Chat GPT with every variation and ask it to create a clean list and a dictionary
#3 Make a note that some people included two specialties in the same response, so I will count mentions instead of responses. Explain that in the article.

In [75]:
df = df.rename(columns={
    "9 - Qual era a especialidade do profissional?": "perp_specialty"
})

df["response_id"] = df.index #give each row a number

def extract_specialties(value):  #this is a function that turns each messy answer into a list of specialties
    if pd.isna(value):
        return []

    text = value.strip().lower()

    specialties = []

    if "gine" in text or "genicologista" in text or "obstetr" in text or text == "go":
        specialties.append("Gynecology/obstetrics")

    if "pediatra" in text:
        specialties.append("Pediatrics")

    if "clinico" in text or "clínico" in text or "clínica" in text or "clinica" in text or "geral" == text:
        specialties.append("General practice/internal medicine")

    if "ortoped" in text or "traumato" in text:
        specialties.append("Orthopedics/traumatology")

    if "cardio" in text:
        specialties.append("Cardiology")

    if "dentista" in text or "odontolog" in text:
        specialties.append("Dentistry")

    if "cirurgi" in text or "cirurgião" in text:
        specialties.append("Surgery")

    if "ultra" in text or "raio x" in text or "ecografo" in text:
        specialties.append("Radiology")

    if "psiquiatr" in text or "psicolog" in text or "psicana" in text:
        specialties.append("Psychiatry/psychology")

    if "nutri" in text or "nutro" in text:
        specialties.append("Nutrition")

    if "enferm" in text:
        specialties.append("Nursing")

    if "dermatolog" in text:
        specialties.append("Dermatology")

    if "otorrino" in text:
        specialties.append("Otorhinolaryngology")

    if "gastro" in text:
        specialties.append("Gastroenterology")

    if "homeopatia" in text:
        specialties.append("Homeopathy")

    if "fisioterapia" in text or "fisioterapeuta" in text:
        specialties.append("Physiotherapy")

    if "reumato" in text:
        specialties.append("Rheumatology")

    if "anestesi" in text:
        specialties.append("Anesthesiology")

    if "mastologista" in text:
        specialties.append("Mastology")

    if len(specialties) == 0:
        specialties.append("Other/unclear")

    return specialties

In [76]:
df["specialty_list"] = df["perp_specialty"].apply(extract_specialties)

#explode it into a specialty-level dataset

df_specialty = df.explode("specialty_list")

df_specialty = df_specialty.rename(columns={
    "specialty_list": "specialty"
})

specialty_counts = df_specialty["specialty"].value_counts()

specialty_percentages = (
    df_specialty["specialty"].value_counts(normalize=True) * 100
).round(1)

print(specialty_counts)
print(specialty_percentages)

specialty
Gynecology/obstetrics                 72
General practice/internal medicine    26
Other/unclear                         17
Pediatrics                            10
Cardiology                            10
Nursing                                9
Orthopedics/traumatology               8
Gastroenterology                       7
Dentistry                              6
Dermatology                            5
Radiology                              5
Surgery                                4
Psychiatry/psychology                  4
Physiotherapy                          3
Otorhinolaryngology                    1
Nutrition                              1
Rheumatology                           1
Anesthesiology                         1
Homeopathy                             1
Mastology                              1
Name: count, dtype: int64
specialty
Gynecology/obstetrics                 37.5
General practice/internal medicine    13.5
Other/unclear                          8.9
Pediatrics                             5.2
Cardiology                             5.2
Nursing                                4.7
Orthopedics/traumatology               4.2
Gastroenterology                       3.6
Dentistry                              3.1
Dermatology                            2.6
Radiology                              2.6
Surgery                                2.1
Psychiatry/psychology                  2.1
Physiotherapy                          1.6
Otorhinolaryngology                    0.5
Nutrition                              0.5
Rheumatology                           0.5
Anesthesiology                         0.5
Homeopathy                             0.5
Mastology                              0.5
Name: proportion, dtype: float64

In [92]:
specialty_counts.to_csv("specialty_counts.csv")

In [93]:
specialty_percentages.to_csv("specialty_percentages.csv")

In [77]:
#TODO: Count all offense rows by location.
all_by_location = df["offense_location_clean"].value_counts(dropna=False)

In [104]:
print(all_by_location)
all_by_location_percentages =((df["offense_location_clean"].value_counts(normalize=True, dropna=False) * 100).round(1))
all_by_location_percentages.to_csv("all_by_location_percentages.csv")

offense_location_clean
Private practice    115
Private hospital     32
Free hospital        18
Free Clinic          17
Other                 5
Name: count, dtype: int64

In [108]:
print(all_by_location_percentages.value_counts(normalize=True, dropna=False))

proportion
61.5    0.2
17.1    0.2
9.6     0.2
9.1     0.2
2.7     0.2
Name: proportion, dtype: float64

In [95]:
all_by_location.to_csv("all_by_location.csv")

In [ ]:
#How do I count offenses by each specialty using column specialty_list, and how many of those happened in each location using column offense_location_clean?
# if specialty_list is already a list-like column:
exploded = df.explode('specialty_list')

# count by specialty
counts_by_specialty = exploded.groupby('specialty_list').size()

# count by specialty and location
counts_by_specialty_and_location = exploded.groupby(
    ['specialty_list', 'offense_location_clean']
).size()
print(counts_by_specialty_and_location)

specialty_list  offense_location_clean
Anesthesiology  Private hospital          1
Cardiology      Free hospital             1
                Private hospital          2
                Private practice          7
Dentistry       Other                     2
                                         ..
Radiology       Other                     1
                Private practice          4
Rheumatology    Private practice          1
Surgery         Free Clinic               1
                Private practice          3
Length: 42, dtype: int64

In [80]:
#download CSV 
counts_by_specialty_and_location.to_csv("offenses_by_specialty_and_location.csv")

QUESTIONS THAT I HAVE

In [81]:
# Are people of different economic status more vulnerable to sexual abuse by a specific type of health professional or location (private vs public/free)?
# What type of abuse is more common among the top 3 specialties (Gynecology/obstetrics, Pediatrics, General practice/internal medicine)?
# Are underage victims (< 18) more likely to be abused by a specific type of health professional?
# What are the most common types of abuse for underage victims (< 18) vs adult victims (18+)?

In [82]:
#Anastasiia resources

#Apify to scrape Twitter posts (maybe)
#sankey
#https://www.occrp.org/en/project/bad-practice/system-failure-banned-doctors-can-easily-move-across-europe-leaving-patients-vulnerable

In [83]:
# Question 1: Are people of different economic status more vulnerable to abuse by a specific type of health professional or location?
# This shows patterns only, not proof of risk.

#ANSWER
# The general idea is:
# 1. Within each economic-status group, what percentage of cases happened in private practice, private hospital, free clinic, free hospital, etc.?
# 2. Within each economic-status group, what percentage of cases happened in each specialty?

econ_location_grouped = df.groupby(["victim_econ_status", "offense_location_clean"])  # group by class and place
econ_by_location = econ_location_grouped.size()  # count rows in each group
econ_by_location = econ_by_location.reset_index(name="count")  # turn counts into a table

location_totals = econ_by_location.groupby("victim_econ_status")["count"].transform("sum")  # total for each class

econ_by_location["percentage_within_economic_status"] = econ_by_location["count"] / location_totals  # make a share
econ_by_location["percentage_within_economic_status"] = econ_by_location["percentage_within_economic_status"] * 100  # make it percent
econ_by_location["percentage_within_economic_status"] = econ_by_location["percentage_within_economic_status"].round(1)  # round it 

print(econ_by_location) 

top_specialties = ["Gynecology/obstetrics", "Pediatrics", "General practice/internal medicine"]  # pick top groups

econ_specialty_grouped = df_specialty.groupby(["victim_econ_status", "specialty"])  # group by class and specialty
econ_by_specialty = econ_specialty_grouped.size()  # count rows in each group. this one returns something that looks like a table, but technically the group names are stored in the index, not regular columns.
econ_by_specialty = econ_by_specialty.reset_index(name="count")  # turns the grouped result back into a normal table, and names the count column "count"

specialty_totals = econ_by_specialty.groupby("victim_econ_status")["count"].transform("sum")  # total for each class

econ_by_specialty["percentage_within_economic_status"] = econ_by_specialty["count"] / specialty_totals  # make a share
econ_by_specialty["percentage_within_economic_status"] = econ_by_specialty["percentage_within_economic_status"] * 100  # make it percent
econ_by_specialty["percentage_within_economic_status"] = econ_by_specialty["percentage_within_economic_status"].round(1)  # round it 

econ_by_top_specialties = econ_by_specialty[econ_by_specialty["specialty"].isin(top_specialties)]  # keep top groups

print(econ_by_top_specialties)

                                   victim_econ_status offense_location_clean  \
0   Classe A - Renda mensal familiar acima de R$11...            Free Clinic
1   Classe A - Renda mensal familiar acima de R$11...          Free hospital
2   Classe A - Renda mensal familiar acima de R$11...                  Other
3   Classe A - Renda mensal familiar acima de R$11...       Private hospital
4   Classe A - Renda mensal familiar acima de R$11...       Private practice
5    Classe B - Renda mensal familiar até   R$ 11.261       Private hospital
6    Classe B - Renda mensal familiar até   R$ 11.261       Private practice
7    Classe C - Renda mensal familiar até    R$ 8.640            Free Clinic
8    Classe C - Renda mensal familiar até    R$ 8.640          Free hospital
9    Classe C - Renda mensal familiar até    R$ 8.640                  Other
10   Classe C - Renda mensal familiar até    R$ 8.640       Private hospital
11   Classe C - Renda mensal familiar até    R$ 8.640       Private practice
12    Classe D - Renda mensal familiar até   R$ 2.004            Free Clinic
13    Classe D - Renda mensal familiar até   R$ 2.004          Free hospital
14    Classe D - Renda mensal familiar até   R$ 2.004                  Other
15    Classe D - Renda mensal familiar até   R$ 2.004       Private hospital
16    Classe D - Renda mensal familiar até   R$ 2.004       Private practice
17    Classe E - Renda mensal familiar até   R$ 1.254            Free Clinic
18    Classe E - Renda mensal familiar até   R$ 1.254          Free hospital
19    Classe E - Renda mensal familiar até   R$ 1.254                  Other
20    Classe E - Renda mensal familiar até   R$ 1.254       Private hospital
21    Classe E - Renda mensal familiar até   R$ 1.254       Private practice

    count  percentage_within_economic_status
0       1                                3.6
1       1                                3.6
2       1                                3.6
3       4                               14.3
4      21                               75.0
5       1                                8.3
6      11                               91.7
7       6                                6.4
8       8                                8.5
9       2                                2.1
10     17                               18.1
11     61                               64.9
12      3                                9.4
13      5                               15.6
14      1                                3.1
15      6                               18.8
16     17                               53.1
17      7                               33.3
18      4                               19.0
19      1                                4.8
20      4                               19.0
21      5                               23.8
                                   victim_econ_status  \
2   Classe A - Renda mensal familiar acima de R$11...
3   Classe A - Renda mensal familiar acima de R$11...
10  Classe A - Renda mensal familiar acima de R$11...
15   Classe B - Renda mensal familiar até   R$ 11.261
16   Classe B - Renda mensal familiar até   R$ 11.261
26   Classe C - Renda mensal familiar até    R$ 8.640
27   Classe C - Renda mensal familiar até    R$ 8.640
31   Classe C - Renda mensal familiar até    R$ 8.640
36    Classe D - Renda mensal familiar até   R$ 2.004
37    Classe D - Renda mensal familiar até   R$ 2.004
45    Classe E - Renda mensal familiar até   R$ 1.254
46    Classe E - Renda mensal familiar até   R$ 1.254

                             specialty  count  \
2   General practice/internal medicine      4
3                Gynecology/obstetrics     13
10                          Pediatrics      1
15  General practice/internal medicine      2
16               Gynecology/obstetrics      6
26  General practice/internal medicine     13
27               Gynecology/obstetrics     30
31                          Pediatrics      9
36  General practice/internal medicine      4
37               Gynecology/obstetrics     14
45  General practice/internal medicine      3
46               Gynecology/obstetrics      9

    percentage_within_economic_status
2                                12.9
3                                41.9
10                                3.2
15                               14.3
16                               42.9
26                               14.0
27                               32.3
31                                9.7
36                               12.1
37                               42.4
45                               14.3
46                               42.9

In [84]:
econ_by_location.to_csv("econ_status_victims_vs_location.csv")

In [85]:
econ_by_top_specialties.to_csv("econ_status_victims_vs_specialty.csv")

In [86]:
# Question 2: What type of abuse is more common among the top 3 specialties?
# This counts abuse mentions, not just respondents.

top_specialties = ["Gynecology/obstetrics", "Pediatrics", "General practice/internal medicine"]  # pick top groups

top_specialty_abuse = df_specialty[df_specialty["specialty"].isin(top_specialties)].copy()  # keep top groups
top_specialty_abuse["abuse_type"] = top_specialty_abuse["types_abuse"].str.split(",")  # split multiple answers
top_specialty_abuse = top_specialty_abuse.explode("abuse_type")  # one abuse type per row
top_specialty_abuse["abuse_type"] = top_specialty_abuse["abuse_type"].str.strip()  # clean spaces

abuse_specialty_grouped = top_specialty_abuse.groupby(["specialty", "abuse_type"])  # group by specialty and abuse
abuse_by_specialty = abuse_specialty_grouped.size()  # count rows in each group
abuse_by_specialty = abuse_by_specialty.reset_index(name="count")  # turn counts into a table

abuse_totals = abuse_by_specialty.groupby("specialty")["count"].transform("sum")  # total for each specialty

abuse_by_specialty["percentage_within_specialty"] = abuse_by_specialty["count"] / abuse_totals  # make a share
abuse_by_specialty["percentage_within_specialty"] = abuse_by_specialty["percentage_within_specialty"] * 100  
abuse_by_specialty["percentage_within_specialty"] = abuse_by_specialty["percentage_within_specialty"].round(1) 

abuse_by_specialty = abuse_by_specialty.sort_values(["specialty", "count"], ascending=[True, False])  # sort biggest first

print("Abuse type by top specialty")  # label the table
print(abuse_by_specialty)  # show the table

Abuse type by top specialty
                             specialty  \
2   General practice/internal medicine
1   General practice/internal medicine
0   General practice/internal medicine
6                Gynecology/obstetrics
5                Gynecology/obstetrics
4                Gynecology/obstetrics
3                Gynecology/obstetrics
10                          Pediatrics
9                           Pediatrics
7                           Pediatrics
8                           Pediatrics

                                           abuse_type  count  \
2   Violação sexual mediante fraude (Tocar de mane...     22
1             Injúria (Cantadas e palavras ofensivas)      7
0   Importunação sexual (Beijos forçados e toques ...      6
6   Violação sexual mediante fraude (Tocar de mane...     50
5             Injúria (Cantadas e palavras ofensivas)     30
4   Importunação sexual (Beijos forçados e toques ...     15
3   Estupro de vulnerável (quando a vítima é menor...      1
10  Violação sexual mediante fraude (Tocar de mane...      7
9   Importunação sexual (Beijos forçados e toques ...      3
7   Estupro de vulnerável (quando a vítima é menor...      1
8   Estupro de vulnerável (quando a vítima é menor...      1

    percentage_within_specialty
2                          62.9
1                          20.0
0                          17.1
6                          52.1
5                          31.2
4                          15.6
3                           1.0
10                         58.3
9                          25.0
7                           8.3
8                           8.3

In [87]:
abuse_by_specialty.to_csv("abuse_by_specialty.csv")

In [88]:
# Question 3: Are underage victims (< 18) more likely to be abused by a specific type of health professional?
# The 16-20 category is excluded because it mixes minors and adults.

df["age_group"] = "Age range overlaps 18"  # start with unclear ages
df.loc[df["victim_age"].isin(["2-5", "6-10", "11-15", "15-17"]), "age_group"] = "Under 18"  # mark minors
df.loc[df["victim_age"].isin(["18-30", "20-30", "31-40", "41-50", "50+"]), "age_group"] = "18+"  # mark adults

df_age_specialty = df.explode("specialty_list")  # one specialty per row
df_age_specialty = df_age_specialty.rename(columns={"specialty_list": "specialty"})  # rename the column
df_age_specialty = df_age_specialty[df_age_specialty["age_group"].isin(["Under 18", "18+"])]  # keep clear ages

age_specialty_grouped = df_age_specialty.groupby(["age_group", "specialty"])  # group by age and specialty
specialty_by_age = age_specialty_grouped.size()  # count rows in each group
specialty_by_age = specialty_by_age.reset_index(name="count")  # turn counts into a table

age_specialty_totals = specialty_by_age.groupby("age_group")["count"].transform("sum")  # total for each age group

specialty_by_age["percentage_within_age_group"] = specialty_by_age["count"] / age_specialty_totals  # make a share
specialty_by_age["percentage_within_age_group"] = specialty_by_age["percentage_within_age_group"] * 100  # make it percent
specialty_by_age["percentage_within_age_group"] = specialty_by_age["percentage_within_age_group"].round(1)  # round it 

specialty_by_age = specialty_by_age.sort_values(["age_group", "count"], ascending=[True, False])  # sort biggest first

print("Specialty by age group")  # label the table
print(specialty_by_age)  # show the table

Specialty by age group
   age_group                           specialty  count  \
6        18+               Gynecology/obstetrics     42
5        18+  General practice/internal medicine     15
12       18+                       Other/unclear      8
1        18+                          Cardiology      6
4        18+                    Gastroenterology      5
..       ...                                 ...    ...
25  Under 18                             Nursing      1
26  Under 18            Orthopedics/traumatology      1
27  Under 18                       Other/unclear      1
29  Under 18                       Physiotherapy      1
30  Under 18               Psychiatry/psychology      1

    percentage_within_age_group
6                          38.9
5                          13.9
12                          7.4
1                           5.6
4                           4.6
..                          ...
25                          2.9
26                          2.9
27                          2.9
29                          2.9
30                          2.9

[31 rows x 4 columns]

In [89]:
specialty_by_age.to_csv("specialty_by_age_group.csv")

In [90]:
# Question 4: What are the most common types of abuse for underage victims (< 18) vs adult victims (18+)?
# The 16-20 category is excluded because it mixes minors and adults.
# This counts abuse mentions, not just respondents.

df_age_abuse = df[df["age_group"].isin(["Under 18", "18+"])].copy()  # keep clear ages
df_age_abuse["abuse_type"] = df_age_abuse["types_abuse"].str.split(",")  # split multiple answers
df_age_abuse = df_age_abuse.explode("abuse_type")  # one abuse type per row
df_age_abuse["abuse_type"] = df_age_abuse["abuse_type"].str.strip()  # clean spaces

age_abuse_grouped = df_age_abuse.groupby(["age_group", "abuse_type"])  # group by age and abuse
abuse_by_age = age_abuse_grouped.size()  # count rows in each group
abuse_by_age = abuse_by_age.reset_index(name="count")  # turn counts into a table

age_abuse_totals = abuse_by_age.groupby("age_group")["count"].transform("sum")  # total for each age group

abuse_by_age["percentage_within_age_group"] = abuse_by_age["count"] / age_abuse_totals  # make a share
abuse_by_age["percentage_within_age_group"] = abuse_by_age["percentage_within_age_group"] * 100  # make it percent
abuse_by_age["percentage_within_age_group"] = abuse_by_age["percentage_within_age_group"].round(1)  # round it 

abuse_by_age = abuse_by_age.sort_values(["age_group", "count"], ascending=[True, False])  # sort biggest first

print("Abuse type by age group")  # label the table
print(abuse_by_age)  # show the table

Abuse type by age group
  age_group                                         abuse_type  count  \
3       18+  Violação sexual mediante fraude (Tocar de mane...     79
2       18+            Injúria (Cantadas e palavras ofensivas)     39
1       18+  Importunação sexual (Beijos forçados e toques ...     35
0       18+  Estupro de vulnerável (quando a vítima é menor...      1
9  Under 18  Violação sexual mediante fraude (Tocar de mane...     26
7  Under 18  Importunação sexual (Beijos forçados e toques ...      9
8  Under 18            Injúria (Cantadas e palavras ofensivas)      7
5  Under 18  Estupro de vulnerável (quando a vítima é menor...      3
6  Under 18  Estupro de vulnerável (quando a vítima é menor...      2
4  Under 18  Estupro (Ato sexual utilizando de violência ou...      1

   percentage_within_age_group
3                         51.3
2                         25.3
1                         22.7
0                          0.6
9                         54.2
7                         18.8
8                         14.6
5                          6.2
6                          4.2
4                          2.1

In [91]:
abuse_by_age.to_csv("abuse_by_age_group.csv")